- tools/travis/build.sh
- tools/travis/setup.sh
Use the scanCode.py (and common travis.cfg) from new "incubator-openwhisk-utilities" repo. under Apache (removing old use of "openwhisk" repo. under openwhisk org.).
> update travis scripts to use scanCode from OW utilities repo.

- .travis.yml
- README.md
- tools/travis/test_openwhisk.sh
This repo will eventually has unit tests and integration tests writen
in Go running against the openwhisk services. However, before this
work item is finished, we need to at least have the existing scala
tests as the goalkeeper to guarentee the code quality of new PRs.
This is the reason why we use this PR as a tentative solution
to fill in the gap of missing test caes. At the same time, we are
working on the test cases for this repo.
> Add the Travis configuration to run integration tests

- whisk/client.go
In order to increase the security of auth, it is necessary to add client
certificate on cli and nginx. So user can use wsk -i property set --cert
openwhisk-client-cert.pem --key openwhisk-client-key.pem to pass client
certificate to nginx. If you don't want to use default client certificate
which system provides, you can create your own client certificate instead
of them.
> Support client certificate on cli and nginx (#2427)

- whisk/action.go
- whisk/activation.go
- whisk/api.go
- whisk/namespace.go
- whisk/package.go
- whisk/rule.go
- whisk/trigger.go
- whisk/util.go
- wski18n/i18n_resources.go
- Created interfaces `Printables` and `Sortables`
- Made Actions, Triggers, Packages, Rules, APIs into Printables and Sortables
- Made Activations into Printables and Sortables, Sort currently undefined
- Made alphabetic sorting default, sort by last update time with --time flag
- Changed sorting default back to last update time, --sort flag for alphabetical sorting
- Updated flag name to "--name-sort"/"-n"
- Updated Docs
- Fixed rule status printing for `wsk list` and `wsk namespace get`
> Allow CLI to sort entities by name (#2326)

- whisk/wskprops.go
- whisk/wskprops_test.go
We need to search for .wskprops under HOME dir instead of GOPATH. In
addition, we support the input of the full path of the wskprops file
instead of the path of the parent dir.
> Replace the path of wskprops' parent dir with the path of wskprops

- whisk/client.go
while command is 'wsk action invoke NNN --result'
Closes: #51
> Skip testing whether the HTTP body indicating a whisk failure result

- whisk/client.go
- whisk/client_test.go
- whisk/wskprops_test.go
> Use a HTTP transport based on the DefaultTransport to pick up proxy support

- whisk/action.go
- whisk/action_test.go
- whisk/client.go
Utilizes new REST interface query parameter to exclude or include code from action get requests.
Depends on: https://github.com/apache/incubator-openwhisk/pull/3109
> Add code query parameter for action get

- whisk/trigger.go
- whisk/trigger_test.go
- Update trigger struct to optionally include a `rules` field
- Add a test to validate `rules` are returned
> Parse new 'rules' field in 'trigger get' response

- whisk/api.go
- whisk/keyvaluearr_test.go
- whisk/shared.go
Add Go SDK support for https://github.com/apache/incubator-openwhisk/pull/3388
Additional changes to follow
- Update CLI to leverage this SDK update (incubator-openwhisk-cli repo)
- Swagger generation updates in the apimgmt createApi action (incubator-openwhisk repo)
> Add support for APIs defined with web actions having the require-whisk-auth annotation

- whisk/start.go
- whisk/start_test.go
there is only one file, start.go providing the whisk.Start and whisk.StartWithArgs functions.
Those are helpers to implement Golang based actions as provided by the openwhisk-runtime-go
Basically they let you to define an action as
func action(event json.RawMessage) (json.RawMessage, error)
and create a main as
func main() { whisk.Start(action) }
or
func main(args []string) { whisk.StartWithArgs(action, args[1:]) } 
the last one is a useful helper to try the function from the command line and make it compatible with the current docker skeleton.
> adding start library for easy implementation of Go actions

- whisk/client.go
As the tid will not be handled as int in the future anymore, this PR changes this assumption in the CLI.
Related PR in the core repository: https://github.com/apache/incubator-openwhisk/pull/3199
> Handle error code (tid) not as int.

- whisk/client.go
Hi openwhiskers!
as per description, I'd like to replace the consumption of the trigger type with an interface. 
This change will enable https://github.com/apache/incubator-openwhisk-cli/pull/353 to run the unit tests for Trigger creation and update. 
Could someone have a look? 
Could be I'm overlooking something due to lack of the codebase knowledge of this repo. 
regards,
Vadim
> Replace trigger service type with interface

- whisk/client.go
I'd like to provide a way to override the existing auth header for client requests using additional headers. Currently, if attempting to add an `"authorization"` header to the `AdditionalHeaders` var the headers get mashed together causing conflicts. This PR rectifies that issue.
> allow additional headers to override auth header val

- .travis.yml
- Godeps/Godeps.json
Travis is failing due to golint as shown below. It appears Go 1.8 is no longer supported (https://github.com/golang/go/issues/28291).
```
$ go get -u golang.org/x/lint/golint
../../../golang.org/x/tools/go/internal/gcimporter/bexport.go:212: obj.IsAlias undefined (type *types.TypeName has no field or method IsAlias)
The command "go get -u golang.org/x/lint/golint" failed and exited with 2 during .
```
> Update Go Version

- whisk/client.go
`IsResponseResultSuccess()` inaccurately generates a debug message indicating a failure.
Closes https://github.com/apache/incubator-openwhisk-client-go/issues/89
> Fix invalid warning message

- .gitignore
- whisk/shared.go
Adds a Concurrency field to Limits to specify the concurrency limit for the action.
Blocked by:
* https://github.com/apache/incubator-openwhisk/pull/2795
> Add Concurrency to Limits

- Godeps/Godeps.json
- Godeps/Readme
- README.md
- vendor/vendor.json
as https://github.com/apache/incubator-openwhisk-cli is already using it.
> as godep is deprecated, move to govendor 

- whisk/activation.go
Added extra columns for output from 'wsk activation list command'. The output now looks as indicated by the screenshot below.
Compared to current output, the following columns have been added:
1. *Datetime*. Date and time of the start of the activation in ISO format
2. *Kind*. The kind of the action, taken from the annotations of the activation. If undefined, *unknown* is output.
3. *Start*. If container was started warm or cold, as indicated by the *initTime* annotation in the activation record.
4. *Duration*. The duration of the activation. Provided in an appropriate measure, such as ms (milliseconds) or s (seconds).
5. *Status*. The outcome of the activation, as indicated by the *statusCode* attribute of the activation record and translated to a descriptive text.
6. *Entity*. The fully …
> Added extra columns to activation records summary rows

- whisk/wskprops.go
This is an attempt to fix wskdeploy issue https://github.com/apache/incubator-openwhisk-wskdeploy/issues/1050
which reported a crash in wskdeploy when the apihost
was a raw host:port without a scheme.
> handle err return from url.Parse in GetUrlBase

- vendor/vendor.json
- whisk/client.go
- whisk/client_test.go
Currently, application errors are not parsed since the application error format is dynamic.  This PR treats the application error as generic JSON, inspecting the "error" field for its data type and handling the type appropriately.
Also, vendor.json is updated to include several missing packages
> Parse an action's application error

- whisk/action.go
It is related to this PR https://github.com/apache/openwhisk/pull/4646
Since there is no `updated` field in the Action structure, `wsk action get ` command doesn't show a `updated` value even though the API passed it.
I think this PR can be merged after the openwhisk-core PR is merged
```
Response body received:
{"annotations":[],"exec":{"kind":"nodejs:10","binary":false},"limits":{"concurrency":1,"logs":10,"memory":128,"timeout":60000},"name":"invokerHealthTestAction0","namespace":"whisk.system","parameters":[],"publish":false,"updated":1569485478259,"version":"0.0.1"}
ok: got action invokerHealthTestAction0
{
"namespace": "whisk.system",
"name": "invokerHealthTestAction0",
"version": "0.0.1",
"exec": {
"kind": "nodejs:10",
"binary": false
},
"limits": {
"timeout": 60000,
"memory": 128, …
```
> Add updated field on Action struct

- whisk/package.go
- whisk/rule.go
- whisk/trigger.go
In the previous PR #129, the updated field was added only to the Action structure. So, I've added this field to the Package, Rule, and Trigger structure as well.
This PR is related to the following two PRs:
- https://github.com/apache/openwhisk/pull/4646 (Serialize `updated` value of entity document in response) 
- https://github.com/apache/openwhisk-client-go/pull/129 (Add updated field on Action struct)
> Add `updated` field on package, rule, and trigger entity

- .travis.yml
the package `stretchr/testify` is not compatible with 1.9.3
> Bump up go version to 1.13.14 for travis

- whisk/action.go
Currently, if passing another annotations, original previous annotation
will be removed and the passed new annotations will be added.
It may give users some confused that why my previous annotation gone.
So it is better to not delete user's previous annotation when adding new
annotation, but at the same time, need to provide a feature that
support to delete annotation by user via ClI, e.g.
```shell
wsk action update hello --del-annotation key1 --del-annotation key2
```
another brother prs to support del annotation: 
* https://github.com/apache/openwhisk-cli/pull/488
* https://github.com/apache/openwhisk/pull/4940
> Add DelAnnotations field to support del annotation

- whisk/client.go
In the following code, `resp` is overwritten by `activation.response` field when called `d.Decode(&errorResponse)`. So `resp.StatusCode` is changed to activation's status code, not HTTP response status code. This causes `parseApplicationError` never calls when parsing action developer error activation.
https://github.com/apache/incubator-openwhisk-client-go/blob/4286a8212a74c40d8950ee76681a67e12c9bf1a0/whisk/client.go#L557-L569
This PR changes to ignore `ErrorResponse.Response` field on parsing.
> Add omit tag to ErrorResponse.Response field

- whisk/activation.go
This PR is a fix for the issue which i raised for the activation's `statusCode`.
For more details about the issue, please click [here](https://github.com/apache/openwhisk-client-go/issues/141)
I have updated `statusCode` on the basis of `status` So that we can get correct `statusCode` according to `status`.
> update status code if action returns error

- whisk/action.go
- whisk/activation.go
Brother prs: 
https://github.com/apache/openwhisk-cli/pull/516
https://github.com/apache/openwhisk-wskdeploy/pull/1153
This pr should be merged firstly
> Support array result

- whisk/activation.go
This PR adds a new method for getting and filtering the total number of activations.
Usage 
```go
func main() {
client, err := whisk.NewClient(http.DefaultClient, nil)
if err != nil {
fmt.Println(err)
os.Exit(-1)
}
options := &whisk.ActivationCountOptions{
Name:  "sample/hello",
Since: 1665662104000,
}
count, resp, err := client.Activations.Count(options)
if err != nil {
fmt.Println(err)
os.Exit(-1)
}
fmt.Println("Returned with status: ", resp.Status)
fmt.Printf("Returned actions: \n %+v", count)
}
```
> Adds support for activation count

- whisk/activation.go
PR #153 converts the whisk.Result type from a map[string]interface{} to an interface{} leaving Result type in whisk.Response as a pointer to Result which is now a pointer to a pointer.
This change updates the Response.Result to remove the double pointer pointing.
> Removes pointer to pointer reference in activations

- whisk/action.go
This PR adds a KeyValueArr field to the action struct.
I am working on adding a `--env` flag to wsk to support adding environment variables during [action initialization], and I figured I need another KeyValueArr when building the Action struct in openwhisk-cli.
The action struct is from the client-go so I'm adding it here, let me know if it's the correct way to do it!
[action initialization]: https://github.com/apache/openwhisk/blob/master/docs/actions-new.md#initialization
> Add Env field 
