whisk/action.go, whisk/activation.go, whisk/api.go, whisk/client.go, whisk/info.go, whisk/namespace.go, whisk/package.go, whisk/rule.go, whisk/trigger.go, whisk/wskerror.go
Updating this repo from openwhisk/tools/cli/go-whisk
Partially closes #3
=> Updates from openwhisk repo

whisk/action.go, whisk/activation.go, whisk/client.go, whisk/sdk.go, whisk/shared.go, whisk/util.go, wski18n/i18n_resources.go
This PR has to merged first in order to get travis build fixed in future.
=> Sync openwhisk

.travis.yml, tools/travis/test_openwhisk.sh
The repo should remove the dependency on test cases in openwhisk cli.
=> Remove the dependency on test cases in openwhisk CLI

.travis.yml, whisk/client.go
This PR sets the default http timout to 60 seconds.
=> Add the default timeout for http request

whisk/client.go
* Updating classes and variables so that they are exported and usable by other modules
* Updating missed debug statements to have case of client -> Client
=> Added changes for classes and variables casing to be get exported and can be used in other places (#2675)

whisk/action.go
* Allow CLI to Save Code from Action
* Formatting changes
* Test refactor
* Update test
* Refactor
* Review updates
* Review updates
=> Allow CLI to Save Code from Action (#2544)

whisk/namespace.go
Due to https://github.com/apache/incubator-openwhisk/issues/3153.
=> Remove client code that will be removed from the API.

whisk/client.go, whisk/client_test.go
Allows for additional HTTP headers to be configured for the HTTP client.
=> Additional HTTP Headers

whisk/wskprops.go
Addressing @rabbah's comment from here https://github.com/apache/incubator-openwhisk-wskdeploy/issues/810
=> Changing default namespace from guest to _

Makefile
=> Add license header to Makefile

LICENSE.txt, licenses/LICENSE-go.txt
Partially-closes: apache/incubator-openwhisk-release#109
=> Add the licenses of the dependencies into LICENSE

README.md
=> Remove the disclaimer and the reference as experimental

whisk/client.go
companion to https://github.com/apache/incubator-openwhisk-cli/pull/344
@rabbah
=> add OS and CPU architecture to user agent header

whisk/client.go
=> Allow NewClient to run concurrently

whisk/client.go
Ran into issues using latest client-go in wsk cli, all non-error responses reporting as failures.
Fixing error logic in #91
=> fixing logic on test for result success

whisk/client.go
Correcting a misspelling in a debug statement.
=> Correct typo in debug statement

whisk/activation.go
This addresses issue #119 and adds dynamic sizing behavior to the *Kind* and *Status* columns, as well as makes sure that the last column doesn't contain whitespaces at the end. This change also requires PR https://github.com/apache/incubator-openwhisk-cli/pull/427.
=> Add dynamic column sizing to wsk activation list command

README.md, tools/travis/build.sh, tools/travis/setup.sh, tools/travis/test_openwhisk.sh, vendor/vendor.json, whisk/action.go, whisk/activation.go, whisk/api.go, whisk/client.go, whisk/info.go, whisk/namespace.go, whisk/package.go, whisk/rule.go, whisk/sdk.go, whisk/trigger.go, whisk/util.go, whisk/wskprops.go, whisk/wskprops_test.go
The key repo. to allow us to start unwinding the dependencies of the CLI and wskdeploy...
=> WIP - Remove 'incubat(ing, ion, or)' designation and disclaimer

README.md, example/example_list_actions.go
Update readme docs with new endpoint & fix example code.
=> chore: update docs & provide example code

CHANGELOG.md, NOTICE.txt
Prep. CHANGELOG and NOTICE files for possible 1.2 release.
=> Prep. for 1.2.0 release

wski18n/i18n_resources.go
=> fix: Fix problematic error returns
